# Generated by Django 4.2.29 on 2026-03-31 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Flim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=200)),
                ('date_sortie', models.IntegerField()),
                ('qte_stock', models.IntegerField()),
                ('prix_location', models.FloatField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.categorie')),
            ],
        ),
    ]
