# Generated by Django 4.2.29 on 2026-04-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_flim_date_creation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flim',
            new_name='Film',
        ),
    ]
