# Generated by Django 4.2.29 on 2026-04-15 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_rename_flim_film'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='Titre',
            new_name='title',
        ),
    ]
